// HTML for the generated pages: the app landing page (same pattern as the
// hand-made app pages — hub styles, hero, features, footer with legal links),
// the legal pages (Inspire Me Now layout: hero with pill + table of contents,
// one card per section) and the home-page card.

import { esc, formatDate, hexToRgb, paragraphs, readable, mix } from './util.mjs';

export const MARKER = '<meta name="generator" content="cybrainx-app-pages">';
export const CSS_MARKER = '/* generated by cybrainx-app-pages';

const UI = {
  en: {
    features: 'Features',
    keyFeatures: 'Key Features',
    plans: 'Plans',
    choosePlan: 'Choose Your Plan',
    screenshots: 'Screenshots',
    legalNav: 'Privacy &amp; Terms',
    support: 'Support',
    backToHub: 'Back to Hub',
    googlePlay: 'Get it on Google Play',
    appStore: 'Download on the App Store',
    comingSoon: 'Coming soon',
    legalEyebrow: 'Privacy &amp; legal',
    legalTitle: 'Transparency first',
    legalText: (name) =>
      `Read how ${name} handles your data and the rules for using the app. You can ask us to delete your data at any time, even without the app.`,
    privacy: 'Privacy Policy',
    privacyHint: 'What we collect, why, and who processes it.',
    terms: 'Terms of Use',
    termsHint: 'The rules for using the app.',
    deletion: 'Data deletion',
    deletionHint: 'Ask us to delete your data, even without the app.',
    supportHint: 'Questions or problems? Email us.',
    allApps: 'All apps',
    updated: 'Last updated',
    toc: 'Table of contents',
    rights: 'All rights reserved.',
  },
  pt: {
    features: 'Recursos',
    keyFeatures: 'Principais Recursos',
    plans: 'Planos',
    choosePlan: 'Escolha Seu Plano',
    screenshots: 'Telas do app',
    legalNav: 'Privacidade e Termos',
    support: 'Suporte',
    backToHub: 'Voltar ao Hub',
    googlePlay: 'Disponível no Google Play',
    appStore: 'Baixar na App Store',
    comingSoon: 'Em breve',
    legalEyebrow: 'Privacidade e termos',
    legalTitle: 'Transparência em primeiro lugar',
    legalText: (name) =>
      `Veja como o ${name} trata seus dados e as regras de uso do app. Você pode pedir a exclusão dos seus dados a qualquer momento, mesmo sem o app.`,
    privacy: 'Política de Privacidade',
    privacyHint: 'O que coletamos, por quê e quem trata os dados.',
    terms: 'Termos de Uso',
    termsHint: 'As regras de uso do app.',
    deletion: 'Exclusão de dados',
    deletionHint: 'Peça a exclusão dos seus dados, mesmo sem o app.',
    supportHint: 'Dúvidas ou problemas? Mande um e-mail.',
    allApps: 'Todos os apps',
    updated: 'Última atualização',
    toc: 'Sumário',
    rights: 'Todos os direitos reservados.',
  },
};

export const ui = (lang) => UI[lang] || UI.en;

export const playUrl = (pkg) => `https://play.google.com/store/apps/details?id=${encodeURIComponent(pkg)}`;

/** Per-app colors for dark (landing) and light (legal) backgrounds. */
export function theme(app) {
  const [c1, c2] = app.colors;
  return {
    c1,
    c2,
    rgb: hexToRgb(c1).join(', '),
    onDark: readable(c1, '#0f172a', '#ffffff'),
    onLight: readable(c1, '#fffaf4', '#000000'),
    softLight: mix(readable(c1, '#fffaf4', '#000000'), '#ffffff', 0.88),
  };
}

function iconTile(app, cls, prefix = '') {
  return app.image
    ? `<div class="${cls}"><img src="${esc(prefix + app.image)}" alt="" loading="lazy"></div>`
    : `<div class="${cls}"><i class="${esc(app.icon)}" aria-hidden="true"></i></div>`;
}

const fonts = `<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;700&family=Inter:wght@400;500;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">`;

// ─── App landing page ───────────────────────────────────────────────────────

export function appPage(app, site, year) {
  const u = ui(app.lang);
  const th = theme(app);
  const name = esc(app.name);
  const url = `${site.baseUrl}/${app.slug}/`;
  const deletion = `../data-deletion-request.html?app=${encodeURIComponent(app.slug)}`;
  const mail = `mailto:${site.email}?subject=${encodeURIComponent(`[${app.name}] ${u.support}`)}`;

  const stores = [];
  if (app.stores?.googlePlay) {
    stores.push(
      `<a class="cta-button" href="${esc(playUrl(app.stores.googlePlay))}" target="_blank" rel="noopener"><i class="fa-brands fa-google-play"></i> ${u.googlePlay}</a>`,
    );
  }
  if (app.stores?.appStore) {
    stores.push(
      `<a class="cta-button secondary" href="${esc(app.stores.appStore)}" target="_blank" rel="noopener"><i class="fa-brands fa-apple"></i> ${u.appStore}</a>`,
    );
  }
  if (!stores.length) stores.push(`<span class="coming-soon"><i class="fa-solid fa-hourglass-half"></i> ${u.comingSoon}</span>`);

  const badge = app.tags?.[0]
    ? `<div class="hero-badge reveal"><i class="${esc(app.tags[0].icon)}"></i> ${esc(app.tags[0].label)}</div>`
    : '';

  const highlights = app.highlights?.length
    ? `\n        <div class="pills reveal">${app.highlights.map((h) => `<span class="pill">${esc(h)}</span>`).join('')}</div>`
    : '';

  const features = app.features?.length
    ? `
    <section id="features" class="apps">
        <h2 class="section-title reveal">${u.keyFeatures}</h2>
        <div class="grid">
${app.features
  .map(
    (f) => `            <div class="card feature reveal">
                <div class="feature-icon"><i class="${esc(f.icon)}"></i></div>
                <h3>${esc(f.title)}</h3>
                <p>${esc(f.text)}</p>
            </div>`,
  )
  .join('\n')}
        </div>
    </section>
`
    : '';

  const screenshots = app.screenshots?.length
    ? `
    <section class="app-section" aria-label="${u.screenshots}">
        <h2 class="section-title reveal">${u.screenshots}</h2>
        <div class="screens reveal">
${app.screenshots.map((s, i) => `            <img src="${esc(s)}" alt="${name} — ${u.screenshots} ${i + 1}" loading="lazy">`).join('\n')}
        </div>
    </section>
`
    : '';

  const plans = app.plans?.length
    ? `
    <section id="plans" class="app-section">
        <h2 class="section-title reveal">${u.choosePlan}</h2>
        <div class="plans">
${app.plans
  .map(
    (pl) => `            <div class="plan${pl.highlight ? ' highlight' : ''} reveal">
                <h3>${esc(pl.name)}</h3>
                ${pl.price ? `<div class="price">${esc(pl.price)}</div>` : ''}
                <ul>${(pl.items || []).map((i) => `<li>${esc(i)}</li>`).join('')}</ul>
            </div>`,
  )
  .join('\n')}
        </div>
    </section>
`
    : '';

  const navLinks = [
    app.features?.length && `<a href="#features">${u.features}</a>`,
    app.plans?.length && `<a href="#plans">${u.plans}</a>`,
    `<a href="#legal">${u.legalNav}</a>`,
    `<a href="${esc(mail)}">${u.support}</a>`,
    `<a href="../index.html" class="back-link">${u.backToHub}</a>`,
  ].filter(Boolean);

  const og = app.image ? `\n    <meta property="og:image" content="${esc(`${url}${app.image}`)}">` : '';
  const jsonLd = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: app.name,
    description: app.tagline,
    url,
    applicationCategory: app.category || 'MobileApplication',
    operatingSystem: [app.stores?.googlePlay && 'Android', app.stores?.appStore && 'iOS'].filter(Boolean).join(', ') || 'Android',
    ...(app.stores?.googlePlay ? { installUrl: playUrl(app.stores.googlePlay) } : {}),
    publisher: { '@type': 'Organization', name: site.company, url: site.baseUrl },
  }).replace(/</g, '\\u003c');

  return `<!DOCTYPE html>
<html lang="${app.lang === 'pt' ? 'pt-BR' : 'en'}">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    ${MARKER}
    <!-- Generated from _apps/${esc(app.slug)}.json — edit that file, not this one. -->
    <title>${name} | ${esc(app.headline)}</title>
    <meta name="description" content="${esc(app.tagline)}">
    <link rel="canonical" href="${esc(url)}">
    <meta property="og:type" content="website">
    <meta property="og:title" content="${name}">
    <meta property="og:description" content="${esc(app.tagline)}">
    <meta property="og:url" content="${esc(url)}">${og}
    <link rel="stylesheet" href="../style.css">
    <link rel="stylesheet" href="../app-pages.css">
    ${fonts}
    <style>:root { --app-1: ${th.c1}; --app-2: ${th.c2}; --app-rgb: ${th.rgb}; --app-link: ${th.onDark}; }</style>
    <script type="application/ld+json">${jsonLd}</script>
</head>

<body class="app-page">
    <nav>
        <div class="logo"><a href="../index.html" style="text-decoration:none; color:inherit;"><i
                    class="fa-solid fa-arrow-left"></i> ${esc(site.company)}</a> / <i class="${esc(app.icon)}"></i> ${name}</div>
        <div class="nav-links">
            ${navLinks.join('\n            ')}
        </div>
    </nav>

    <header class="hero app-hero">
        ${iconTile(app, 'app-icon reveal')}
        ${badge}
        <h1 class="reveal">${esc(app.headline)}</h1>
        <div class="reveal">${paragraphs(app.description)}</div>
        <div class="store-buttons reveal">
            ${stores.join('\n            ')}
        </div>${highlights}
    </header>
${features}${screenshots}${plans}
    <section id="legal" class="app-section app-legal">
        <p class="section-eyebrow reveal">${u.legalEyebrow}</p>
        <h2 class="section-title reveal">${u.legalTitle}</h2>
        <p class="legal-intro reveal">${esc(app.privacyBlurb || u.legalText(app.name))}</p>
        <div class="legal-links">
            <a class="legal-link reveal" href="privacy-policy.html"><i class="fa-solid fa-shield-halved"></i><span><strong>${u.privacy}</strong>${u.privacyHint}</span></a>
            <a class="legal-link reveal" href="terms-of-use.html"><i class="fa-solid fa-file-contract"></i><span><strong>${u.terms}</strong>${u.termsHint}</span></a>
            <a class="legal-link reveal" href="${esc(deletion)}"><i class="fa-solid fa-user-slash"></i><span><strong>${u.deletion}</strong>${u.deletionHint}</span></a>
            <a class="legal-link reveal" href="${esc(mail)}"><i class="fa-solid fa-envelope"></i><span><strong>${u.support}</strong>${u.supportHint}</span></a>
        </div>
    </section>

    <footer>
        <div class="footer-logo"><i class="fa-solid fa-cube"></i> ${esc(site.company)}</div>
        <div class="footer-links">
            <a href="privacy-policy.html">${u.privacy}</a>
            <span class="footer-sep">·</span>
            <a href="terms-of-use.html">${u.terms}</a>
            <span class="footer-sep">·</span>
            <a href="${esc(deletion)}">${u.deletion}</a>
            <span class="footer-sep">·</span>
            <a href="../index.html#apps">${u.allApps}</a>
        </div>
        <p class="footer-copy">&copy; ${year} ${esc(site.company)}. ${name}.</p>
    </footer>

    <script src="../script.js"></script>
</body>

</html>
`;
}

// ─── Legal pages (Inspire Me Now layout) ────────────────────────────────────

/**
 * `doc` comes from legal.mjs. The date and year are left as placeholders so
 * the caller can hash the content and keep the "Last updated" date stable
 * until the text itself changes.
 */
export function legalPage(app, site, doc, kind) {
  const u = ui(app.lang);
  const th = theme(app);
  const name = esc(app.name);
  const file = kind === 'privacy' ? 'privacy-policy.html' : 'terms-of-use.html';
  const deletion = `../data-deletion-request.html?app=${encodeURIComponent(app.slug)}`;
  const current = (f) => (f === file ? ' aria-current="page"' : '');
  const plainLede = doc.lede.replace(/<[^>]+>/g, '');

  return `<!DOCTYPE html>
<html lang="${app.lang === 'pt' ? 'pt-BR' : 'en'}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    ${MARKER}
    <meta name="content-hash" content="%%HASH%%">
    <!-- Generated from _apps/${esc(app.slug)}.json — edit that file, not this one. -->
    <title>${name} ${esc(doc.title)}</title>
    <meta name="description" content="${esc(plainLede)}" />
    <link rel="canonical" href="${esc(`${site.baseUrl}/${app.slug}/${file}`)}" />
    <link rel="stylesheet" href="../app-pages.css" />
    <style>:root { --accent: ${th.onLight}; --accent-soft: ${th.softLight}; }</style>
  </head>
  <body class="legal-doc">
    <header class="topbar">
      <a class="brand" href="../index.html">${esc(site.company)}</a>
      <nav aria-label="${name}">
        <a href="index.html">${name}</a>
        <a href="privacy-policy.html"${current('privacy-policy.html')}>${u.privacy}</a>
        <a href="terms-of-use.html"${current('terms-of-use.html')}>${u.terms}</a>
      </nav>
    </header>

    <main class="container">
      <section class="hero">
        <span class="pill">${esc(doc.pill)}</span>
        <h1>${name}</h1>
        <p class="lede">
          ${doc.lede}
        </p>
        <p class="meta" data-updated="%%UPDATED_ISO%%">
          ${u.updated}: %%UPDATED%%
        </p>

        <nav class="toc" aria-label="${u.toc}">
${doc.sections.map((s) => `          <a href="#${esc(s.id)}">${esc(s.title)}</a>`).join('\n')}
        </nav>
      </section>
${doc.sections
  .map(
    (s) => `
      <section class="section" id="${esc(s.id)}">
        <h2>${esc(s.title)}</h2>
${indent(s.html, 8)}
      </section>`,
  )
  .join('\n')}
    </main>

    <footer class="site-footer">
      <div class="footer-links">
        <a href="index.html">${name}</a>
        <a href="privacy-policy.html"${current('privacy-policy.html')}>${u.privacy}</a>
        <a href="terms-of-use.html"${current('terms-of-use.html')}>${u.terms}</a>
        <a href="${esc(deletion)}">${u.deletion}</a>
        <a href="../index.html#apps">${u.allApps}</a>
      </div>
      <p>&copy; %%YEAR%% ${esc(site.company)}. ${u.rights}</p>
    </footer>
  </body>
</html>
`;
}

function indent(html, spaces) {
  const pad = ' '.repeat(spaces);
  return html
    .split('\n')
    .filter((line) => line.trim())
    .map((line) => pad + line)
    .join('\n');
}

// ─── Home page card ─────────────────────────────────────────────────────────

export function homeCard(app) {
  const th = theme(app);
  const icon = app.image
    ? `<img src="${esc(`${app.slug}/${app.image}`)}" alt="" loading="lazy" style="width:100%;height:100%;object-fit:cover;border-radius:inherit;">`
    : `<i class="${esc(app.icon)}"></i>`;
  const tags = (app.tags || [])
    .slice(0, 2)
    .map((tag) => `<span class="tag"><i class="${esc(tag.icon)}"></i> ${esc(tag.label)}</span>`)
    .join('\n                        ');
  return `            <!-- ${esc(app.name)} (generated from _apps/${esc(app.slug)}.json) -->
            <a href="${esc(app.slug)}/index.html" class="card reveal">
                <div class="card-glow"
                    style="background: radial-gradient(circle, rgba(${th.rgb},0.16) 0%, transparent 70%);"></div>
                <div class="card-icon" style="background: linear-gradient(135deg, ${th.c1}, ${th.c2});">
                    ${icon}
                </div>
                <div class="card-content">
                    <h3>${esc(app.name)}</h3>
                    <p>${esc(app.tagline)}</p>
                    <div class="card-tags">
                        ${tags}
                    </div>
                    <span class="card-arrow"><i class="fa-solid fa-arrow-right"></i></span>
                </div>
            </a>
`;
}

// ─── Shared stylesheet ──────────────────────────────────────────────────────

export const APP_PAGES_CSS = `${CSS_MARKER} — do not edit; change _generator/templates.mjs */

/* ============ App landing pages (body.app-page, on top of ../style.css) ============ */

body.app-page::before {
    background: radial-gradient(circle at 18% 12%, rgba(var(--app-rgb), 0.16) 0%, transparent 45%),
                radial-gradient(circle at 85% 80%, rgba(var(--app-rgb), 0.08) 0%, transparent 50%),
                #0f172a;
}

.app-page .app-hero { min-height: 88vh; }
.app-page .app-hero h1 { max-width: 16ch; }
.app-page .app-hero p { margin-left: auto; margin-right: auto; }

.app-icon {
    width: 104px; height: 104px;
    border-radius: 28px;
    display: flex; align-items: center; justify-content: center;
    background: linear-gradient(135deg, var(--app-1), var(--app-2));
    color: #fff;
    font-size: 2.8rem;
    margin-bottom: 1.6rem;
    box-shadow: 0 18px 50px rgba(var(--app-rgb), 0.35);
    overflow: hidden;
}
.app-icon img { width: 100%; height: 100%; object-fit: cover; }

.app-page .hero-badge {
    color: var(--app-link);
    background: rgba(var(--app-rgb), 0.12);
    border-color: rgba(var(--app-rgb), 0.35);
}

.app-page .cta-button { background: linear-gradient(135deg, var(--app-1), var(--app-2)); }
.app-page .cta-button:hover { box-shadow: 0 12px 28px rgba(var(--app-rgb), 0.35); }
.app-page .cta-button.secondary {
    background: rgba(255, 255, 255, 0.06);
    border: 1px solid rgba(255, 255, 255, 0.18);
}

.store-buttons { display: flex; flex-wrap: wrap; gap: 0.8rem; justify-content: center; }

.coming-soon {
    display: inline-flex; align-items: center; gap: 0.5rem;
    padding: 0.8rem 1.6rem;
    border-radius: 50px;
    border: 1px dashed rgba(var(--app-rgb), 0.6);
    color: var(--app-link);
    font-weight: 600;
}

.pills { display: flex; flex-wrap: wrap; gap: 0.6rem; justify-content: center; margin-top: 2rem; }
.pills .pill {
    padding: 0.45rem 1rem;
    border-radius: 99px;
    background: rgba(255, 255, 255, 0.06);
    border: 1px solid rgba(255, 255, 255, 0.1);
    color: var(--text-secondary);
    font-size: 0.85rem;
}

.app-page .card.feature { cursor: default; }
.app-page .card.feature:hover { border-color: rgba(var(--app-rgb), 0.5); }
.app-page .card.feature p { margin-bottom: 0; }
.feature-icon {
    width: 48px; height: 48px;
    border-radius: 14px;
    display: flex; align-items: center; justify-content: center;
    background: rgba(var(--app-rgb), 0.14);
    color: var(--app-link);
    font-size: 1.2rem;
    margin-bottom: 1.1rem;
}

.app-section { padding: 5rem 8%; }
.app-page section.apps { padding-top: 3rem; }

.screens {
    display: flex; gap: 1rem;
    overflow-x: auto;
    scroll-snap-type: x mandatory;
    padding-bottom: 1rem;
}
.screens img {
    height: 440px; width: auto;
    border-radius: 22px;
    border: var(--glass-border);
    scroll-snap-align: start;
    flex-shrink: 0;
}

.plans {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: 1.5rem;
    max-width: 900px;
    margin: 0 auto;
}
.plan {
    background: var(--bg-card);
    border: var(--glass-border);
    border-radius: 20px;
    padding: 2rem;
}
.plan.highlight { border-color: rgba(var(--app-rgb), 0.6); box-shadow: 0 18px 40px rgba(var(--app-rgb), 0.15); }
.plan h3 { font-size: 1.3rem; margin-bottom: 0.4rem; }
.plan.highlight h3 { color: var(--app-link); }
.plan .price { font-size: 2rem; font-weight: 800; margin-bottom: 1rem; }
.plan ul { list-style: none; }
.plan li { color: var(--text-secondary); padding: 0.35rem 0; }
.plan li::before { content: '✓'; color: var(--app-link); margin-right: 0.6rem; font-weight: 700; }

.app-legal { text-align: center; }
.legal-intro { color: var(--text-secondary); max-width: 620px; margin: -1rem auto 2.5rem; }
.legal-links {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 1rem;
    max-width: 1000px;
    margin: 0 auto;
    text-align: left;
}
.legal-link {
    display: flex; gap: 1rem; align-items: flex-start;
    padding: 1.3rem 1.4rem;
    border-radius: 18px;
    background: var(--bg-card);
    border: var(--glass-border);
    color: var(--text-secondary);
    text-decoration: none;
    font-size: 0.88rem;
    transition: transform 0.3s, border-color 0.3s;
}
.legal-link:hover { transform: translateY(-4px); border-color: rgba(var(--app-rgb), 0.55); }
.legal-link i { color: var(--app-link); font-size: 1.3rem; margin-top: 0.15rem; }
.legal-link strong { display: block; color: var(--text-primary); font-size: 1rem; margin-bottom: 0.2rem; }

.app-page .nav-links a.back-link { color: var(--app-link); }
.app-page .footer-links a:hover { color: var(--app-link); }

@media (max-width: 768px) {
    .app-section { padding: 4rem 5%; }
    .screens img { height: 360px; }
}

/* ============ Legal pages (body.legal-doc) — Inspire Me Now layout ============ */

.legal-doc {
    --bg: #f7f2ea;
    --card: #fffaf4;
    --text: #1f2933;
    --muted: #5d6b78;
    --line: #e7ddd0;
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    line-height: 1.65;
    background:
        radial-gradient(circle at top left, color-mix(in srgb, var(--accent) 10%, transparent), transparent 28%),
        linear-gradient(180deg, #fbf7f1 0%, var(--bg) 100%);
    color: var(--text);
    min-height: 100vh;
}
.legal-doc * { box-sizing: border-box; }

.legal-doc .topbar {
    width: min(920px, calc(100% - 32px));
    margin: 0 auto;
    padding: 20px 0 0;
    display: flex;
    flex-wrap: wrap;
    gap: 10px 20px;
    align-items: center;
    justify-content: space-between;
}
.legal-doc .brand {
    font-weight: 800;
    letter-spacing: 0.02em;
    color: var(--text);
    text-decoration: none;
}
.legal-doc .topbar nav { display: flex; flex-wrap: wrap; gap: 6px; }
.legal-doc .topbar nav a {
    padding: 6px 12px;
    border-radius: 999px;
    color: var(--muted);
    text-decoration: none;
    font-size: 14px;
    font-weight: 600;
}
.legal-doc .topbar nav a:hover { color: var(--text); }
.legal-doc .topbar nav a[aria-current="page"] { background: var(--accent-soft); color: var(--accent); }

.legal-doc .container {
    width: min(920px, calc(100% - 32px));
    margin: 0 auto;
    padding: 24px 0 40px;
}

.legal-doc .hero,
.legal-doc .section {
    background: var(--card);
    border: 1px solid var(--line);
    border-radius: 24px;
    box-shadow: 0 18px 45px rgba(31, 41, 51, 0.07);
}
.legal-doc .hero { padding: 32px; margin-bottom: 20px; }

.legal-doc .pill {
    display: inline-flex;
    align-items: center;
    padding: 6px 12px;
    border-radius: 999px;
    background: var(--accent-soft);
    color: var(--accent);
    font-size: 14px;
    font-weight: 700;
    letter-spacing: 0.02em;
    text-transform: uppercase;
}

.legal-doc h1 { margin: 16px 0 10px; font-size: clamp(32px, 5vw, 48px); line-height: 1.08; }
.legal-doc h2 { margin: 0 0 14px; font-size: 26px; line-height: 1.2; }
.legal-doc h3 { margin: 24px 0 10px; font-size: 18px; line-height: 1.3; }
.legal-doc p, .legal-doc li { font-size: 16px; }
.legal-doc .lede { font-size: 18px; color: var(--muted); max-width: 720px; }
.legal-doc .meta { margin-top: 18px; color: var(--muted); font-size: 15px; }

.legal-doc .toc {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 12px;
    margin-top: 24px;
}
.legal-doc .toc a {
    display: block;
    text-decoration: none;
    color: var(--text);
    background: #ffffff;
    border: 1px solid var(--line);
    border-radius: 16px;
    padding: 14px 16px;
    font-weight: 600;
}
.legal-doc .toc a:hover { border-color: #cfc2b2; }

.legal-doc .section { padding: 28px 30px; margin-top: 18px; scroll-margin-top: 16px; }
.legal-doc .section > :last-child,
.legal-doc .hero > :last-child { margin-bottom: 0; }
.legal-doc ul { margin: 10px 0 0 20px; padding: 0; }
.legal-doc a { color: var(--accent); }

.legal-doc .note {
    border-left: 4px solid var(--accent);
    padding: 14px 16px;
    background: color-mix(in srgb, var(--accent-soft) 45%, #ffffff);
    border-radius: 12px;
    color: var(--muted);
    margin-top: 14px;
}

.legal-doc .grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
    gap: 16px;
}
.legal-doc .card {
    background: #ffffff;
    border: 1px solid var(--line);
    border-radius: 18px;
    padding: 18px;
}
.legal-doc .card strong { display: block; margin-bottom: 8px; }

.legal-doc .site-footer {
    width: min(920px, calc(100% - 32px));
    margin: 0 auto;
    padding: 0 0 48px;
    color: var(--muted);
    font-size: 14px;
    text-align: center;
}
.legal-doc .site-footer .footer-links {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 6px 18px;
    margin-bottom: 8px;
}
.legal-doc .site-footer a { color: var(--muted); }
.legal-doc .site-footer a[aria-current="page"] { color: var(--accent); font-weight: 700; }

@media (max-width: 640px) {
    .legal-doc .container { width: min(100% - 20px, 920px); padding-top: 16px; padding-bottom: 28px; }
    .legal-doc .topbar, .legal-doc .site-footer { width: min(100% - 20px, 920px); }
    .legal-doc .hero, .legal-doc .section { border-radius: 20px; padding: 22px 18px; }
}
`;
